
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  id: wifi_id
#  manual_ip:
#    static_ip: ${static_ip}
#    gateway: 192.168.123.1
#    subnet: 255.255.255.0
  domain: .iot
  
# Enable fallback hotspot (captive portal) in case wifi connection fails (like, we change the password!!)
#ap:
#  ssid: ${devicename}_hotspot
#  password: leonardo
#  manual_ip:
#    static_ip: 192.168.1.1
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0
#captive_portal:

# Probably not a good idea on an ESP8266
# https://esphome.io/components/web_server.html
web_server:
  port: 80

# Enable logging
logger:

# This makes it talk via the esphome integration, we use mqtt instead
# api:

# Enable over-the-air updates
ota:
  - platform: esphome
    password: ""
  
# Don't need a web server right now
#web_server:

sensor:
  - platform: uptime
    name: ${devicename} uptime

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_dbm

# only works with "api"
#time:
#  - platform: homeassistant
#    id: homeassistant_time

# That's all!
