
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  domain: .iot
  
# Enable fallback hotspot (captive portal) in case wifi connection fails (like, we change the password!!)
  ap:
    ssid: ${esphome.name}_hotspot
    password: !secret wifi_fallback_password

captive_portal:

# Probably not good on an ESP8266
# but handy for debugging
# https://esphome.io/components/web_server.html
#web_server:
#  port: 80

# Enable logging
logger:

# Choose either api or mqtt
# Esphome integration
# api:
#time:
#  time only works with "api"
#  - platform: homeassistant
#    id: homeassistant_time
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable over-the-air updates
ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_dbm

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: IP Address
    mac_address:
      name: Mac address
      id: mac_address
      
  - platform: version
    name: ESPHome version
    id: esphome_version
    hide_timestamp: True

# That's all!
