
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  id: wifi_id
#  manual_ip:
#    static_ip: ${static_ip}
#    gateway: 192.168.123.1
#    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails (like, we change the password!!)
  ap:
    ssid: ${devicename}_hotspot
    password: leonardo

logger:

# This makes it talk via the esphome integration
api:

captive_portal:

# Enable over-the-air updates
ota:
  - platform: esphome
  
# Don't need a web server right now
#web_server:

sensor:
  - platform: uptime
    name: ${devicename} uptime

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_dbm

time:
  - platform: homeassistant
    id: homeassistant_time

# That's all!
