substitutions:
  devicename: esp12e
  upper_devicename: esp
  static_ip: 192.168.123.200
<<: !include common.yaml

api:

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp12e

light:
  - platform: binary
    id: builtin_led
    name: $devicename builtin led
    restore_mode: ALWAYS_OFF
    output: output_builtin_led
output:
  - platform: gpio
    id: output_builtin_led
    pin: GPIO2
    inverted: True

# Enable the API (so we can talk to Home Assistant)
api:

# enable Over The Air upgrades
ota:


