# Refer to 
# https://github.com/carefulcomputer/espHomeOnFeitDimmer/blob/master/dimmer.yaml

substitutions:
  devicename: feit1
  upper_devicename: Feit1
  static_ip: 192.168.123.211
<<: !include common.yaml

api:

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

# Register the Tuya MCU connection
tuya:

# The UART is used by Tuya so logging 
# will stop it from functioning.
logger:
  baud_rate: 0
  level: NONE

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# This dimmer has control for a light 
# an on/off switch and two up/down buttons
# but pretty much that's out of our control
# because of the Tuya MCU.

light:
  - platform: "tuya" 
    name: "dimmer"
    switch_datapoint: 1
    dimmer_datapoint: 2
    min_value: 10
    max_value: 1000
    retain: false