substitutions:
  devicename: feit01
  upper_devicename: Feit1
  static_ip: 192.168.123.211
<<: !include common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# This dimmer has control for a light 
# an on/off switch and two up/down buttons

light:
  - platform: "tuya" 
    name: "dimmable light"
    switch_datapoint: 1
    dimmer_datapoint: 2
