substitutions:
  devicename: m5atom
  friendly_name: "M5Stack Atom"

packages:
  common: !include common.yaml
  m5atom: !include m5atom_hardware.yaml

esphome:
  # name the esphome build will use
  name: m5atom
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  # I could add boot stuff here

# Perhaps cache state
#preferences:
#  flash_write_interval: 5min
