# The M5 Atom Matrix (https://docs.m5stack.com/en/core/ATOM%20Matrix has
#
#   * USB-C UART port at GPIO1, GPIO3, and also GPIO0, EN
#   * Button GPIO39
#   * 5x5 WS2812c matrix GPIO27
#   * Grove GPIO32(white), GPIO26(yellow), 5V out(red), GND(black
#   * Pins: GPIO21(SCL), GPIO25(SDA), GPIO22, GPIO19, GPIO23, GPIO33,
#             5V out, GND, 3V3 out
#   * MPU6886 Temperature, 6-axis IMU IC on I2C addr 0x68 GPIO21, GPIO25
#   * Infrared transmit on GPIO12
#

esphome:
  name: ${devicename}
  platformio_options: 
    upload_speed: 115200

esp32:
  variant: esp32
  board: m5stack-atom
  framework: 
    type: esp-idf

binary_sensor:
  # Status Sensor - Shows if device is online or offline in Home Assistant
  - platform: status
    name: "${friendly_name} Status"

  # Physical Button - The built-in button on GPIO41
  - platform: gpio
    # The name that appears in Home Assistant
    name: "${friendly_name} Button"

    # Button configuration
    pin:
      number: GPIO39

      # Inverted means pressed=LOW, released=HIGH (common for buttons with pullup)
      inverted: true

      mode:
        input: true
        #pullup: true # not needed here

    # Filters clean up the button signal
    filters:
      # Debouncing: Ignore button bouncing for 10 milliseconds
      - delayed_off: 10ms

remote_transmitter:
  - id: ir_transmitter
    pin: GPIO12
    carrier_duty_percent: 50%
    non_blocking: true

sensor:
  - platform: mpu6886
    address: 0x68
    accel_x:
      name: "MPU6886 Accel X"
    accel_y:
      name: "MPU6886 Accel Y"
    accel_z:
      name: "MPU6886 Accel z"
    gyro_x:
      name: "MPU6886 Gyro X"
    gyro_y:
      name: "MPU6886 Gyro Y"
    gyro_z:
      name: "MPU6886 Gyro z"
    temperature:
      name: "MPU6886 Temperature"
      id: mpu_temp
    update_interval: 30s

spi:
  clk_pin: GPIO23
  miso_pin: GPIO33
  mosi_pin: GPIO19

i2c:
   - id: bus_a
     sda: GPIO25
     scl: GPIO21
     scan: True

color:
  - id: GREEN
    red: 0%
    green: 100%
    blue: 0%
  - id: BLUE
    red: 0%
    green: 0%
    blue: 100%
  - id: RED
    red: 100%
    green: 0%
    blue: 0%
  - id: YELLOW
    red: 100%
    green: 100%
    blue: 0%

# That's all!
