substitutions:
  devicename: martn_jerry_mj_s01
  friendly_name: "Martin Jerry MJ-S01"

packages:
  common: !include common.yaml

esphome:
  # name the esphome build will use
  name: mj-s01
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  on_boot:
    - priority: 600
      then:
      # RED only indicates we're starting up
        - switch.turn_on: red_led
        - switch.turn_off: blue_led
    - priority: 200
      then:
      # BLUE only means network is up
        - switch.turn_off: red_led
        - switch.turn_on: blue_led

# We ignore state so we never cache it.
preferences:
  flash_write_interval: never

esp8266:
  board: esp01_1m

switch:
  - platform: gpio
    id: relay
    name: Relay
    pin: GPIO12
    on_turn_on:
      - switch.turn_on: blue_led
      - switch.turn_on: red_led
    on_turn_off:
      - switch.turn_on: blue_led
      - switch.turn_off: red_led
      - light.turn_off: diagnostic_led

  - platform: gpio
    id: red_led
    name: Red LED
    pin: GPIO4
    inverted: True

  - platform: gpio
    id: blue_led
    name: Blue LED
    pin: GPIO5
    inverted: True

# This light is on the ESP12F,
# not on the Tuya modules. Useful
# for testing before installation.
light:
  - platform: binary
    id: diagnostic_led
    name: "MCU LED"
    restore_mode: ALWAYS_ON
    output: output_led
output:
  - platform: gpio
    id: output_led
    pin: GPIO2
    inverted: True

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
    on_press:
      switch.toggle: relay

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_dbm

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: IP Address

# This allows remote restart via MQTT
button:
  - platform: restart
    id: restart_button
    name: Remote restart
    entity_category: diagnostic
