#
#   2026-02-08
#   THIS IS AN MCU TRANSPLANT config for the Martin Jerry US-SS01 smart switch.
#

substitutions:
  devicename: martin_jerry_us_ss01
  friendly_name: "Martin Jerry US-SS01" 

packages:
  common: !include common.yaml

esphome:
  # name the esphome build will use
  name: mj-ss01
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  on_boot:
    # Both lights (purple) means it's still loading
    - priority: 600
      then:
        - light.turn_off: blue_led
    - priority: 200
      then:
      # BLUE means network is up
        - light.turn_on: blue_led

# Cache state so light can come back on after random stupid restarts
preferences:
  flash_write_interval: 5min

esp32:
  variant: esp32c3
  flash_size: 4MB
  # ESP-IDF is 2-3X faster and 40% smaller! W00T 
  framework:
    type: esp-idf

switch:
  - platform: gpio
    id: relay
    name: Relay
    pin: GPIO3
    on_turn_on:
      - light.turn_on: blue_led
    on_turn_off:
      - light.turn_on: blue_led
    # Try to restore last state on power cycle but default to OFF
    restore_mode: RESTORE_DEFAULT_OFF

light:
  - platform: binary
    id: blue_led
    name: "Blue LED"
    restore_mode: ALWAYS_OFF
    output: output_blue
output:
  - platform: gpio
    id: output_blue
    pin: GPIO4
    inverted: True

# Now using status_led component for red led
status_led:
  pin: 
    number: GPIO5
    inverted: True

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      # shared with UART1_RXD
      number: GPIO20
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 5min
    id: wifi_dbm

  # Not sure what is running here
  - platform: adc
    pin: GPIO1
    name: "Analog"

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: IP Address

# This allows remote restart via MQTT
button:
  - platform: restart
    id: restart_button
    name: Remote restart
    entity_category: diagnostic
