substitutions:
  devicename: martin_jerry_us_ss01
  friendly_name: "Martin Jerry US-SS01" 

packages:
  common: !include common.yaml

esphome:
  # name the esphome build will use
  name: mj-ss01
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  on_boot:
    # Both lights on dimly means it's still loading
    - priority: 600
      then:
      # RED indicates we're starting up
        - switch.turn_on: red_led
        - switch.turn_off: blue_led
    - priority: 200
      then:
      # BLUE means network is up
        - switch.turn_off: red_led
        - switch.turn_on: blue_led

# We ignore state so we never cache it.
preferences:
  flash_write_interval: never

bk72xx:
  board: wb2s

switch:
  - platform: gpio
    id: relay
    name: Relay
    pin: PWM2
    on_turn_on:
      - switch.turn_on: blue_led
      - switch.turn_on: red_led
    on_turn_off:
      - switch.turn_on: blue_led
      - switch.turn_off: red_led

  - platform: gpio
    id: red_led
    name: Red LED
    pin: PWM4
    inverted: true

  - platform: gpio
    id: blue_led
    name: Blue LED
    pin: PWM5
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      # shared with UART1_RXD
      number: P10
      mode: INPUT_PULLUP
      inverted: true
    name: Button
    on_press:
      - switch.toggle: relay

sensor:
  - platform: uptime
    name: Uptime

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_dbm

  # Not sure what is running here
  - platform: adc
    pin: ADC3
    name: "Analog"

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: IP Address

# This allows remote restart via MQTT
button:
  - platform: restart
    id: restart_button
    name: Remote restart
    entity_category: diagnostic
