substitutions:
  devicename: martin_jerry_us-ss01
  friendly_name: "Martin Jerry US-SS01" 
  static_ip: "DHCP mode"

packages:
  common: !include common.yaml

esphome:
  # name the esphome build will use
  name: mj-ss01
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  on_boot:
    # Both lights on dimly means it's still loading
    - priority: 600
      then:
      # RED indicates we're starting up
        - switch.turn_on: red_led
        - switch.turn_off: blue_led
    - priority: 200
      then:
      # BLUE means network is up
        - switch.turn_off: red_led
        - switch.turn_on: blue_led

# We ignore state on boot
preferences:
  flash_write_interval: never

bk72xx:
  board: wb2s

switch:
  - platform: gpio
    id: relay
    name: Relay
    pin: PWM2
    on_turn_on:
      - switch.turn_on: blue_led
      - switch.turn_on: red_led
    on_turn_off:
      - switch.turn_on: blue_led
      - switch.turn_off: red_led

  - platform: gpio
    pin: PWM4
    id: red_led
    name: Red LED
    inverted: true

  - platform: gpio
    pin: PWM5
    id: blue_led
    name: Blue LED
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      # shared with UART1_RXD
      number: P10
      mode: INPUT_PULLUP
      inverted: true
    name: Button
    on_press:
      - switch.toggle: relay

sensor:
  # Not sure what is running here
  - platform: adc
    pin: ADC3
    name: "Analog"

# This allows remote restart via MQTT
button:
  - platform: restart
    id: restart_button
    name: Remote restart
    entity_category: diagnostic
