substitutions:
  devicename: mj1
  upper_devicename: MJ1
  static_ip: 192.168.123.221
<<: !include common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

light:
  - platform: binary
    id: red_led
    name: ${upper_devicename} red led
    restore_mode: ALWAYS_ON
    output: output_red_led

  - platform: binary
    id: blue_led
    name: ${upper_devicename} blue led
    restore_mode: ALWAYS_OFF
    output: output_blue_led

output:
  - platform: gpio
    id: output_red_led
    pin: GPIO4
    inverted: True

  - platform: gpio
    id: output_blue_led
    pin: GPIO5
    inverted: True

binary_sensor:
  - platform: gpio
    id: button_1
    name: ${upper_devicename} Button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - light.turn_on: blue_led
        - light.turn_off: red_led
    on_release:
      then:
        - delay: 3s
        - light.turn_off: blue_led
        - delay: 3s
        - light.turn_on: red_led
        - delay: 3s
        - light.turn_off: red_led


