substitutions:
  devicename: wemos02
  upper_devicename: Wemos02
  static_ip: 192.168.123.204
<<: !include common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

captive_portal:

logger:

i2c:
  scl: D1
  sda: D2

font:
  - file: "DejaVuSansMono.ttf"
    id: dejavu
    size: 28
    glyphs: "0123456789:.APM "    
    
light:
  - platform: monochromatic
    id: builtin_light
    name: ${upper_devicename} light
    output: output_bltinled
    restore_mode: ALWAYS_OFF
    default_transition_length: 10ms

output:
  - platform: esp8266_pwm
    id: output_led
    pin: D3
    inverted: True

  - platform: esp8266_pwm
    id: output_bltinled
    pin: D4
    inverted: True

# LDR Light Sensor
sensor:
  - platform: adc
    pin: A0
    name: ${upper_devicename} lux
    update_interval: 30s
    unit_of_measurement: lx
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: gpio
    id: motion
    name: ${upper_devicename} Motion
    device_class: motion
    pin:
      number: D5
      inverted: False
      mode: INPUT
    on_press:
      then:
        - light.turn_on: builtin_light
    on_release:
      then:
        - delay: 10s
        - light.turn_off: builtin_light

  - platform: gpio
    id: button_1
    name: ${upper_devicename} Button
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - light.turn_on: builtin_light
    on_release:
      then:
        - delay: 3s
        - light.turn_off: builtin_light
      
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    brightness: .50
    lambda: |-
      if (id(motion).state) {
        it.strftime(10, 2, id(dejavu), "%I:%M%p", id(homeassistant_time).now());
      } else {
        it.fill(COLOR_OFF);
      }
time:
  - platform: homeassistant
    id: homeassistant_time

