substitutions:
  devicename: wemos-rfid
  upper_devicename: WEMOS-RFID
  static_ip: 192.168.123.240
<<: !include common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

logger:

spi:
  clk_pin: D5
  miso_pin: D6
  mosi_pin: D7

rc522_spi:
  cs_pin: GPIO15 # this makes no sense to me
  on_tag: # any tag makes the light go on
    then:
      - light.turn_on: light_1
      - delay: 1s
      - light.turn_off: light_1
  reset_pin: D3

# Send an event when this exact tag shows up
binary_sensor:
  - platform: rc522
    uid: 04-0C-6A-B2-7B-2B-81
    name: "RFID 1"

  - platform: rc522
    uid: 04-A3-A0-BA-7B-2B-80
    name: "RFID 2"

  - platform: rc522
    uid: 04-85-A0-BA-7B-2B-80
    name: "RFID 3"

  - platform: rc522
    uid: 04-86-A0-BA-7B-2B-80
    name: "RFID 4"

  - platform: rc522
    uid: 23-8C-D5-E5
    name: "Blue tag"

  - platform: rc522
    uid: 04-73-3F-32-85-2A-80
    name: "AM 1"

  - platform: rc522
    uid: 04-87-25-32-85-2A-80
    name: "AM 2"

  - platform: rc522
    uid: 04-8C-41-32-85-2A-80
    name: "AM 3"

  - platform: rc522
    uid: 43-FB-31-13
    name: "RFID Card"

# SDA   D8
# IRQ   NC
    
light:
  - platform: monochromatic
    id: light_1
    name: RFID Builtin LED
    output: output_rfidled
    restore_mode: ALWAYS_OFF
    default_transition_length: 10ms

output:
  - platform: esp8266_pwm
    id: output_rfidled
    pin: D4
    inverted: True

