substitutions:
  devicename: wemos03
  upper_devicename: Wemos03
  static_ip: 192.168.123.205
<<: !include common.yaml

api:

logger:

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini

i2c:
  scl: D1
  sda: D2

font:
  - file: "DejaVuSansMono.ttf"
    id: dejavu
    size: 28
    glyphs: "0123456789:.APM "    
    
light:
  - id: builtin_light
    platform: monochromatic
    name: ${upper_devicename} light
    output: output_bltinled
    restore_mode: ALWAYS_OFF
    default_transition_length: 500ms

  - id: neopixel
    platform: neopixelbus
    pin: RX
    method: ESP8266_DMA
    type: GRBW
    num_leds: 1
    name: ${upper_devicename} NeoPixel
    restore_mode: ALWAYS_OFF
    default_transition_length: 500ms
    
output:
  - id: output_bltinled
    platform: esp8266_pwm
    pin: D4
    inverted: True
    
binary_sensor:
  - platform: gpio
    id: motion
    name: ${upper_devicename} Motion
    device_class: motion
    pin:
      number: D5
      inverted: False
      mode: INPUT
    on_press:
      then:
        - light.turn_on: builtin_light
    on_release:
      then:
        - delay: 5s
        - light.turn_off: builtin_light
        - light.turn_off: neopixel

  - platform: gpio
    id: button_1
    name: ${upper_devicename} Button
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - light.turn_on:
            id: neopixel
            brightness: 50%
            red: 50%
            green: 0%
            blue: 0%
    on_release:
      then:
        - delay: 3s
        - light.turn_off: neopixel
      
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    address: 0x3C
    brightness: .50
    lambda: |-
      if (id(motion).state) {
        it.strftime(10, 2, id(dejavu), "%I:%M%p", id(homeassistant_time).now());
      } else {
        it.fill(COLOR_OFF);
      }
time:
  - platform: homeassistant
    id: homeassistant_time

